name: baby_tracker
description: Baby Tracker app for offline signal tracking and prioritized sync.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  uuid: ^4.5.1
  http: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  battery_plus: ^6.0.2
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  flutter_background_geolocation: ^4.15.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
